

CREATE TABLE ORDERS (
    order_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_id bigint NOT NULL,
    payment_channel varchar(20),
    iscod boolean,
    order_status varchar(20),
    order_createdon bigint,
    total_amount double,
    shipping_address varchar(20),
    PRIMARY KEY (order_id)
);

CREATE TABLE ORDER_LINEITEM(
orderlineitem_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
sku_id bigint NOT NULL,
order_id bigint NOT NULL,
item_qty int,
PRIMARY KEY (orderlineitem_id),
foreign key (order_id) references ORDERS(order_id)
);

INSERT INTO ORDERS values(1,1,'COD',true,'confirmed',1540463527105,100,'xx');
INSERT INTO ORDER_LINEITEM VALUES(1,1,1,1);
